### ISSUE TITLE
Incompatible with tokio-tungstenite 0.12

### ISSUE THREAD

**Issue by lmcgartland** [elast0ny/wamp_async#9]
When building this library (either from crates.io or git), several errors occur including:
```
error[E0277]: the trait bound `tokio::net::TcpStream: tokio::io::async_read::AsyncRead` is not satisfied
error[E0277]: the trait bound `tokio_tls::TlsStream<tokio::net::TcpStream>: tokio::io::async_read::AsyncRead` is not satisfied
error[E0277]: the trait bound `tokio::net::TcpStream: tokio::io::async_write::AsyncWrite` is not satisfied
error[E0277]: the trait bound `tokio_tls::TlsStream<tokio::net::TcpStream>: tokio::io::async_write::AsyncWrite` is not satisfied
error[E0599]: no method named `send` found for struct `tokio_tungstenite::WebSocketStream<tokio_tungstenite::stream::Stream<tokio::net::TcpStream, tokio_tls::TlsStream<tokio::net::TcpStream>>>` in the current scope
```

It appears that the source of these errors stems from the version of tokio-tungstenite being used. I'm able to build with up to v0.11 of that library, but it breaks with v0.12 (which is used by default).

The way the Cargo.toml for this package is written doesn't specify with enough granularity which version should be used. I can open a PR to specify a version under or equal to v0.11?

**Comment by frol** [comment]
> I can open a PR to specify a version under or equal to v0.11?

Yes, please do it. Let’s be explicit about the version and the next step we should take (a separate PR) is to migrate to the newer tokio-tungstenite

**Comment by lmcgartland** [comment]
@frol Should the PR be based on the 0.1.x series or the 0.2.x series on master? I haven't looked into what the differences are. Also, after a little more work, I was able to get an upgrade to tokio 0.3 and tokio-tungstenite, I'll open up a separate issue for that.
